package:
  format-version: "1.0.0"
  name: "csp_apps_cec173x"
  version: "v3.3.0"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.16.0"


